[build]
  # Build command (if you add a build process later)
  command = "npm run build"
  # Directory to publish (current directory for now)
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Performance headers
    Cache-Control = "public, max-age=31536000"

# Cache CSS and JS files for 1 year
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images for 1 year
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect rules (if needed)
[[redirects]]
  from = "/home"
  to = "/"
  status = 301

# Form handling (for contact forms)
[[forms]]
  name = "newsletter"
